// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: double.proto

package doublepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoubleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *DoubleRequest) Reset() {
	*x = DoubleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_double_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleRequest) ProtoMessage() {}

func (x *DoubleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_double_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleRequest.ProtoReflect.Descriptor instead.
func (*DoubleRequest) Descriptor() ([]byte, []int) {
	return file_double_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type DoubleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DoubleResponse) Reset() {
	*x = DoubleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_double_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleResponse) ProtoMessage() {}

func (x *DoubleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_double_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleResponse.ProtoReflect.Descriptor instead.
func (*DoubleResponse) Descriptor() ([]byte, []int) {
	return file_double_proto_rawDescGZIP(), []int{1}
}

func (x *DoubleResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_double_proto protoreflect.FileDescriptor

var file_double_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x28, 0x0a, 0x0e, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x52, 0x0a, 0x0d, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x12, 0x17, 0x2e, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_double_proto_rawDescOnce sync.Once
	file_double_proto_rawDescData = file_double_proto_rawDesc
)

func file_double_proto_rawDescGZIP() []byte {
	file_double_proto_rawDescOnce.Do(func() {
		file_double_proto_rawDescData = protoimpl.X.CompressGZIP(file_double_proto_rawDescData)
	})
	return file_double_proto_rawDescData
}

var file_double_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_double_proto_goTypes = []interface{}{
	(*DoubleRequest)(nil),  // 0: doublepb.DoubleRequest
	(*DoubleResponse)(nil), // 1: doublepb.DoubleResponse
}
var file_double_proto_depIdxs = []int32{
	0, // 0: doublepb.DoubleService.Double:input_type -> doublepb.DoubleRequest
	1, // 1: doublepb.DoubleService.Double:output_type -> doublepb.DoubleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_double_proto_init() }
func file_double_proto_init() {
	if File_double_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_double_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_double_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_double_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_double_proto_goTypes,
		DependencyIndexes: file_double_proto_depIdxs,
		MessageInfos:      file_double_proto_msgTypes,
	}.Build()
	File_double_proto = out.File
	file_double_proto_rawDesc = nil
	file_double_proto_goTypes = nil
	file_double_proto_depIdxs = nil
}
