// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: multiples.proto

package multiplespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiplesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *MultiplesRequest) Reset() {
	*x = MultiplesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiples_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplesRequest) ProtoMessage() {}

func (x *MultiplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiples_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplesRequest.ProtoReflect.Descriptor instead.
func (*MultiplesRequest) Descriptor() ([]byte, []int) {
	return file_multiples_proto_rawDescGZIP(), []int{0}
}

func (x *MultiplesRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type MultiplesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums int32 `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`
}

func (x *MultiplesResponse) Reset() {
	*x = MultiplesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiples_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplesResponse) ProtoMessage() {}

func (x *MultiplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiples_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplesResponse.ProtoReflect.Descriptor instead.
func (*MultiplesResponse) Descriptor() ([]byte, []int) {
	return file_multiples_proto_rawDescGZIP(), []int{1}
}

func (x *MultiplesResponse) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

var File_multiples_proto protoreflect.FileDescriptor

var file_multiples_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x70, 0x62, 0x22, 0x24,
	0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x22, 0x27, 0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x32, 0x62, 0x0a,
	0x10, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4e, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x1d,
	0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiples_proto_rawDescOnce sync.Once
	file_multiples_proto_rawDescData = file_multiples_proto_rawDesc
)

func file_multiples_proto_rawDescGZIP() []byte {
	file_multiples_proto_rawDescOnce.Do(func() {
		file_multiples_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiples_proto_rawDescData)
	})
	return file_multiples_proto_rawDescData
}

var file_multiples_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiples_proto_goTypes = []interface{}{
	(*MultiplesRequest)(nil),  // 0: multiplespb.MultiplesRequest
	(*MultiplesResponse)(nil), // 1: multiplespb.MultiplesResponse
}
var file_multiples_proto_depIdxs = []int32{
	0, // 0: multiplespb.MultiplesService.Multiples:input_type -> multiplespb.MultiplesRequest
	1, // 1: multiplespb.MultiplesService.Multiples:output_type -> multiplespb.MultiplesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiples_proto_init() }
func file_multiples_proto_init() {
	if File_multiples_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiples_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiples_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiplesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiples_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiples_proto_goTypes,
		DependencyIndexes: file_multiples_proto_depIdxs,
		MessageInfos:      file_multiples_proto_msgTypes,
	}.Build()
	File_multiples_proto = out.File
	file_multiples_proto_rawDesc = nil
	file_multiples_proto_goTypes = nil
	file_multiples_proto_depIdxs = nil
}
