// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package greetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetDeadlineServiceClient is the client API for GreetDeadlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetDeadlineServiceClient interface {
	// Unary with deadline
	GreetDeadline(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type greetDeadlineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetDeadlineServiceClient(cc grpc.ClientConnInterface) GreetDeadlineServiceClient {
	return &greetDeadlineServiceClient{cc}
}

func (c *greetDeadlineServiceClient) GreetDeadline(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greetpb.GreetDeadlineService/GreetDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetDeadlineServiceServer is the server API for GreetDeadlineService service.
// All implementations must embed UnimplementedGreetDeadlineServiceServer
// for forward compatibility
type GreetDeadlineServiceServer interface {
	// Unary with deadline
	GreetDeadline(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedGreetDeadlineServiceServer()
}

// UnimplementedGreetDeadlineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetDeadlineServiceServer struct {
}

func (UnimplementedGreetDeadlineServiceServer) GreetDeadline(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetDeadline not implemented")
}
func (UnimplementedGreetDeadlineServiceServer) mustEmbedUnimplementedGreetDeadlineServiceServer() {}

// UnsafeGreetDeadlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetDeadlineServiceServer will
// result in compilation errors.
type UnsafeGreetDeadlineServiceServer interface {
	mustEmbedUnimplementedGreetDeadlineServiceServer()
}

func RegisterGreetDeadlineServiceServer(s grpc.ServiceRegistrar, srv GreetDeadlineServiceServer) {
	s.RegisterService(&GreetDeadlineService_ServiceDesc, srv)
}

func _GreetDeadlineService_GreetDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetDeadlineServiceServer).GreetDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetpb.GreetDeadlineService/GreetDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetDeadlineServiceServer).GreetDeadline(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetDeadlineService_ServiceDesc is the grpc.ServiceDesc for GreetDeadlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetDeadlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greetpb.GreetDeadlineService",
	HandlerType: (*GreetDeadlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetDeadline",
			Handler:    _GreetDeadlineService_GreetDeadline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet.proto",
}
